### ISSUE TITLE
Documentation models.py

### ISSUE THREAD

**Issue by Sterre26** [Stefanie-B/python-intermediate-inflammation#6]
Documentation not complete/correct for:
- def load_csv >> no return defined
- def daily_stddev >> documentation not for std for return value
- def daily_normalise >> no documentation for input and output
- for all functions add documentation for output shape of functions

**Comment by Stefanie-B** [comment]
@Sterre26 can you elaborate on what you mean by ```def daily_stddev >> documentation not for std for return value```?

**Comment by Sterre26** [comment]
The documentation says `:returns: Mean values measured on each day` whereas it should say `:returns: Standard deviation values on each day`
